### ISSUE TITLE
file could not be read

### ISSUE THREAD

**Issue by shywolf91** [alfablac/TGC-Ripper#2]
The file could not be read:
The underlying connection was closed: An unexpected error occurred on a send.

**Comment by alfablac** [comment]
Hard to point where this problem can be.
If all files necessary to run this are set to the root folder of the application:

Do you get the "Scrapping page.." message when running the executable?

If yes, this might be some update TGP made to the pages, which I think [this line](https://github.com/alfablac/TGC-Ripper/blob/a5b430832a38f50f15ddc4407d6120cd93de589d/Program.cs#L105) would throw an error

I don't have an active subscription anymore, but I will try to use a trial to check that, no promises.

**Comment by shywolf91** [comment]
Only thing I get from running the program is the above output.

But it may be that line. The url I get from TGP is https://www.thegreatcoursesplus.com/films/title/ and right clicking on video you'll gewt powered by jw player

**Comment by alfablac** [comment]
oh. I think I put the wrong filename in the description. Did you put the course links on a list.txt file or links.txt as the descriptions says? links.txt wouldn't work because the code is searching for a list.txt file.

**Comment by shywolf91** [comment]
I put the course in a list.txt

I used the files located in the releases section of github

**Comment by shywolf91** [comment]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/2508167/53412747-2def9900-3998-11e9-84aa-8a5cd63d4494.gif)

**Comment by shywolf91** [comment]
No change from trying to use the released exe you provided but when I tried to build it using visual studio (hopefully correctly) I get the following output
[output.txt](https://github.com/alfablac/TGC-Ripper/files/2908462/output.txt)

**Comment by shywolf91** [comment]
Finally got it to work

The exe provided didn't work but when I finally built a new exe in visual studio it worked again
