### ISSUE TITLE
course-info class

### ISSUE THREAD

**Issue by 21tesla** [alfablac/TGC-Ripper#3]
When looking in the html of a course, I cannot find the class called "**course-info**". 

The closest class to it is "course-info-container" with item-prop as an h2 formatted entry.

Do you have a sample page to test? 

```
no such element: Unable to locate element: {"method":"xpath","selector":"//*[@class='course-info']/h1"}
  (Session info: headless chrome=88.0.4324.150)
```

**Comment by alfablac** [comment]
Hello @21tesla 
I would consider TGC-Ripper as a deprecated ripper. 
TGC changed the site's layout and moved from serving the full file to an HLS stream a few months ago.
I ended up writing https://github.com/alfablac/tgc-dl
tgc-dl was effectively tested on the entire site last year.
